### ISSUE TITLE
无法刷新，一直用旧的sw文件

### ISSUE THREAD

**Issue by Ben199011** [youwasborntodo/pwas#3]
![image](https://user-images.githubusercontent.com/30291896/77141085-a4d16580-6ab6-11ea-8b7a-5daa9c9e474f.png)
存在了两个文件，一直用旧的缓存，没用新的

**Comment by Ben199011** [comment]
我把旧的那个文件手动删除，代码就是读取最新的

**Comment by youwasborntodo** [comment]
出现这种原因是因为中途你修改过配置文件中的构建名称；或者是因为中间版本有所调整导致，这个不是问题，如果中途修改过缓存名称，确实需要手动在调试工具中删除旧的缓存，后续我将在缓存配置名称使用注意事项中写出这一点！感谢提问！
